apiVersion: apps/v1
kind: Deployment
metadata:
 name: mongodb-deployment
 labels:
  app: mongodb
spec:
 replicas: 1
 selector:
  matchLabels:
   app: mongodb 
 template: 
  metadata:
   labels:
    app: mongodb
  spec:
   containers:
   - name: mongodb
     image: mongo
     ports:
     - containerPort: 27017
---
apiVersion: v1
kind: Service
metadata:
 name: mongo
spec:
 selector:
  app: mongodb 
 ports:
  - protocol: TCP
    port: 27017
    targetPort: 27017
---  
apiVersion: apps/v1
kind: Deployment
metadata:
 name: app-express
 labels:
  app: app-express
spec:
 replicas: 1
 selector:
  matchLabels:
   app: app-express
 template: 
  metadata:
   labels:
    app: app-express
  spec:
   containers:
   - name: app-express
     image: sahilorsunny/appimage:1.0
     ports:
     - containerPort: 9000
---
apiVersion: v1
kind: Service
metadata:
 name: app-express-service
spec:
 selector:
  app: app-express 
 type: LoadBalancer
 ports:
  - protocol: TCP
    port: 9000
    targetPort: 9000
    nodePort: 30000

 

